FILEO PRINTO[1] = "{SCENARIO_DIR}\output\NTLEG1PK_{alt}{year}.NTL"
FILEO PRINTO[2] = "{SCENARIO_DIR}\output\NTLEG1OP_{alt}{year}.NTL"
FILEO PRINTO[3] = "{SCENARIO_DIR}\output\PCWALK_{alt}{year}.DAT"
;FILEO PRINTO[1] = "{SCENARIO_DIR}\output\NTLEG1PK_{alt}{year}.NTL"
;FILEO PRINTO[2] = "{SCENARIO_DIR}\output\NTLEG1OP_{alt}{year}.NTL"
;FILEO PRINTO[3] = "{SCENARIO_DIR}\output\PCWALK_{alt}{year}.DAT"

*REWALK.EXE
*if exist rewalk.dmp del rewalk.dmp
