; Do not change filenames or add or remove FILEI/FILEO statements using an editor. Use Cube/Application Manager.

;*del {SCENARIO_DIR}\output\@PURP@UTIL_CW_0CAR.MAT
;*del {SCENARIO_DIR}\output\@PURP@UTIL_CW_1CAR.MAT
;*del {SCENARIO_DIR}\output\@PURP@UTIL_CW_2CAR.MAT
;*del {SCENARIO_DIR}\output\@PURP@UTIL_MD_0CAR.MAT
;*del {SCENARIO_DIR}\output\@PURP@UTIL_MD_1CAR.MAT
;*del {SCENARIO_DIR}\output\@PURP@UTIL_MD_2CAR.MAT
;*del {SCENARIO_DIR}\output\@PURP@UTIL_NT_0CAR.MAT
;*del {SCENARIO_DIR}\output\@PURP@UTIL_NT_1CAR.MAT
;*del {SCENARIO_DIR}\output\@PURP@UTIL_NT_2CAR.MAT

if ({MC_Calib}>0)
